# Generated by Django 3.2.13 on 2022-06-16 21:24

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to='whatever'),
            preserve_default=False,
        ),
    ]
